/**
 * gerber_gen.c — Gerber File Generation Implementation
 *
 * Generates RS-274X and X2 compliant Gerber photoplot files from
 * PCB geometry descriptions.
 *
 * The generation process follows the Ucamco specification:
 *   1. Header comments and format directives
 *   2. Aperture definitions (%ADD)
 *   3. Aperture macro definitions (%AM) if needed
 *   4. Graphics state setting (polarity, unit, etc.)
 *   5. Draw/flash/move commands
 *   6. Trailer (M02*)
 *
 * References:
 *   - Ucamco RS-274X Format Specification, §6 File Structure
 *   - IPC-2581, Consolidated Design Data Exchange Format
 */

#include "gerber_gen.h"
#include "gerber.h"
#include "pcb_geometry.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include <stdio.h>

/* ─── Internal: Coordinate Formatting ───────────────────────────── */

/**
 * Format a floating-point coordinate according to the writer's state.
 * Returns number of characters written to buf.
 */
static int write_gerber_coord(GerberWriter *writer, double value, char *buf)
{
    int64_t int_val = gerber_phys_to_int(value, writer->state.dec_digits);
    return format_coordinate(int_val,
                             writer->state.int_digits,
                             writer->state.dec_digits,
                             writer->state.zero_suppress,
                             buf);
}

/**
 * Write X coordinate to file.
 * Format: "X123456" (no decimal point, integer value)
 */
static void emit_x(GerberWriter *writer, double x)
{
    char buf[32];
    write_gerber_coord(writer, x, buf);
    fprintf(writer->output, "X%s", buf);
}

/**
 * Write Y coordinate.
 */
static void emit_y(GerberWriter *writer, double y)
{
    char buf[32];
    write_gerber_coord(writer, y, buf);
    fprintf(writer->output, "Y%s", buf);
}

/**
 * Write I (X center offset) for arcs.
 */
static void emit_i(GerberWriter *writer, double i)
{
    char buf[32];
    write_gerber_coord(writer, i, buf);
    fprintf(writer->output, "I%s", buf);
}

/**
 * Write J (Y center offset) for arcs.
 */
static void emit_j(GerberWriter *writer, double j)
{
    char buf[32];
    write_gerber_coord(writer, j, buf);
    fprintf(writer->output, "J%s", buf);
}

/**
 * Emit D-code command: D01 (draw), D02 (move), D03 (flash),
 *   or D10+ (aperture select).
 */
static void emit_d(GerberWriter *writer, int d_code)
{
    fprintf(writer->output, "D%02d*\n", d_code);
}

/* ─── Writer Initialization ─────────────────────────────────────── */

void gerber_writer_init(GerberWriter *writer, FILE *output,
                        GerberUnit unit, int int_digits, int dec_digits,
                        GerberZeroSuppression zero_supp)
{
    assert(writer != NULL);
    assert(output != NULL);

    memset(writer, 0, sizeof(GerberWriter));
    writer->output = output;

    gerber_state_init(&writer->state);
    writer->state.unit          = unit;
    writer->state.int_digits    = int_digits;
    writer->state.dec_digits    = dec_digits;
    writer->state.zero_suppress = zero_supp;

    aperture_table_init(&writer->apertures);
    macro_table_init(&writer->macros);
    x2_file_attr_init(&writer->x2_attr);
    writer->x2_enabled   = 0;
    writer->region_active = 0;
    writer->op_count     = 0;

    /* Emit RS-274X header */
    fprintf(output, "%%FSLAX%d%dY%d%d*%%\n",
            int_digits, dec_digits, int_digits, dec_digits);
    if (unit == GERBER_UNIT_MM) {
        fprintf(output, "%%MOMM*%%\n");
    } else {
        fprintf(output, "%%MOIN*%%\n");
    }
    fprintf(output, "G04 Gerber file generated by mini-gerber-gen *\n");
}

void gerber_writer_set_x2(GerberWriter *writer, const X2FileAttribute *attr)
{
    assert(writer != NULL);
    assert(attr != NULL);

    writer->x2_attr = *attr;
    /* Deep copy part attributes */
    if (attr->n_part_attrs > 0 && attr->part_attrs != NULL) {
        writer->x2_attr.part_attrs = (X2PartAttribute*)malloc(
            (size_t)attr->n_part_attrs * sizeof(X2PartAttribute));
        if (writer->x2_attr.part_attrs != NULL) {
            memcpy(writer->x2_attr.part_attrs, attr->part_attrs,
                   (size_t)attr->n_part_attrs * sizeof(X2PartAttribute));
        }
    }

    writer->x2_enabled = 1;

    /* Emit X2 file function attribute */
    const char *func_names[] = {
        "Copper", "SoldermaskTop", "SoldermaskBot",
        "SilkscreenTop", "SilkscreenBot",
        "SolderPasteTop", "SolderPasteBot",
        "Profile", "Drill", "Rout", "Legend",
        "Glue", "Carbon", "Gold", "Peelable"
    };
    if (attr->function <= X2_FUNC_PEELABLE) {
        fprintf(writer->output, "%%TF.FileFunction,%s,L%d*%%\n",
                func_names[attr->function], attr->layer_number);
    }
    if (attr->part_name[0] != '\0') {
        fprintf(writer->output, "%%TF.Part,Single*%%\n");
        fprintf(writer->output, "%%TF.Job,%s,%s*%%\n",
                attr->part_name, attr->revision);
    }
}

/* ─── Aperture Definition ───────────────────────────────────────── */

/**
 * Write an aperture definition directive to the Gerber file.
 *
 * Format: %ADD{code}{shape},{params}*%
 *
 * Circle:  %ADD10C,0.5*%
 * Rectangle: %ADD11R,1.0X0.5*%
 * Obround: %ADD12O,1.0X0.5*%
 * Polygon: %ADD13P,1.0X6X0.0*%  (diameter X n_vertices X rotation)
 * Macro:   %ADD14MACRONAME*%
 */
static void emit_aperture_def(FILE *fp, const ApertureDef *ap)
{
    fprintf(fp, "%%ADD%d", ap->d_code);

    switch (ap->shape) {
    case APERTURE_CIRCLE:
        fprintf(fp, "C,%.4f", ap->param1);
        break;
    case APERTURE_RECTANGLE:
        fprintf(fp, "R,%.4fX%.4f", ap->param1, ap->param2);
        break;
    case APERTURE_OBROUND:
        fprintf(fp, "O,%.4fX%.4f", ap->param1, ap->param2);
        break;
    case APERTURE_POLYGON:
        fprintf(fp, "P,%.4fX%dX%.1f",
                ap->param1, ap->n_vertices, ap->rotation);
        break;
    case APERTURE_MACRO:
        fprintf(fp, "%s", ap->name);
        break;
    default:
        fprintf(fp, "C,0.1");  /* Fallback */
        break;
    }

    if (ap->hole_diameter > 0.0) {
        fprintf(fp, "X%.4f", ap->hole_diameter);
    }

    fprintf(fp, "*%%\n");
}

int gerber_writer_add_aperture(GerberWriter *writer, ApertureShape shape,
                               double p1, double p2, double p3,
                               double hole_dia)
{
    assert(writer != NULL);

    int d_code = aperture_table_add(&writer->apertures, shape,
                                    p1, p2, p3, hole_dia, 0.0);
    if (d_code < 0) {
        return -1;
    }

    /* Emit the definition in the file */
    int idx = aperture_table_find(&writer->apertures, d_code);
    if (idx >= 0) {
        emit_aperture_def(writer->output, &writer->apertures.apertures[idx]);
    }

    return d_code;
}

/* ─── Drawing Operations ────────────────────────────────────────── */

void gerber_writer_select_aperture(GerberWriter *writer, int d_code)
{
    assert(writer != NULL);

    writer->state.current_dcode = d_code;
    fprintf(writer->output, "D%d*\n", d_code);
    writer->op_count++;
}

void gerber_writer_move_to(GerberWriter *writer, double x, double y)
{
    assert(writer != NULL);
    assert(writer->output != NULL);

    emit_x(writer, x);
    emit_y(writer, y);
    fprintf(writer->output, "D02*\n");

    writer->state.current_pos.x = gerber_phys_to_int(x, writer->state.dec_digits);
    writer->state.current_pos.y = gerber_phys_to_int(y, writer->state.dec_digits);
    writer->op_count++;
}

void gerber_writer_flash_at(GerberWriter *writer, double x, double y)
{
    assert(writer != NULL);

    emit_x(writer, x);
    emit_y(writer, y);
    fprintf(writer->output, "D03*\n");

    writer->state.current_pos.x = gerber_phys_to_int(x, writer->state.dec_digits);
    writer->state.current_pos.y = gerber_phys_to_int(y, writer->state.dec_digits);
    writer->op_count++;
}

void gerber_writer_draw_to(GerberWriter *writer, double x, double y)
{
    assert(writer != NULL);

    if (writer->region_active) {
        /* Inside a G36..G37 region, coordinates are region vertices */
        emit_x(writer, x);
        emit_y(writer, y);
        fprintf(writer->output, "D01*\n");
    } else {
        /* Normal draw: G01 is implied by D01 */
        emit_x(writer, x);
        emit_y(writer, y);
        fprintf(writer->output, "D01*\n");
    }

    writer->state.current_pos.x = gerber_phys_to_int(x, writer->state.dec_digits);
    writer->state.current_pos.y = gerber_phys_to_int(y, writer->state.dec_digits);
    writer->op_count++;
}

void gerber_writer_draw_arc_to(GerberWriter *writer, double x, double y,
                               double cx, double cy, int cw)
{
    assert(writer != NULL);

    /* Emit appropriate G-code for arc direction */
    if (cw) {
        fprintf(writer->output, "G02");
    } else {
        fprintf(writer->output, "G03");
    }
    fprintf(writer->output, "*\n");

    emit_x(writer, x);
    emit_y(writer, y);
    emit_i(writer, cx);
    emit_j(writer, cy);
    fprintf(writer->output, "D01*\n");

    /* Restore linear interpolation */
    fprintf(writer->output, "G01*\n");

    writer->state.current_pos.x = gerber_phys_to_int(x, writer->state.dec_digits);
    writer->state.current_pos.y = gerber_phys_to_int(y, writer->state.dec_digits);
    writer->op_count++;
}

void gerber_writer_begin_region(GerberWriter *writer)
{
    assert(writer != NULL);
    assert(!writer->region_active);  /* No nested regions */

    fprintf(writer->output, "G36*\n");
    writer->region_active = 1;
    writer->op_count++;
}

void gerber_writer_end_region(GerberWriter *writer)
{
    assert(writer != NULL);
    assert(writer->region_active);

    fprintf(writer->output, "G37*\n");
    writer->region_active = 0;
    writer->op_count++;
}

void gerber_writer_set_polarity(GerberWriter *writer, GerberPolarity polarity)
{
    assert(writer != NULL);

    if (polarity == GERBER_POLARITY_DARK) {
        fprintf(writer->output, "%%LPD*%%\n");
    } else {
        fprintf(writer->output, "%%LPC*%%\n");
    }
    writer->state.polarity = polarity;
}

void gerber_writer_comment(GerberWriter *writer, const char *comment)
{
    assert(writer != NULL);
    assert(comment != NULL);

    fprintf(writer->output, "G04 %s *\n", comment);
}

void gerber_writer_step_repeat(GerberWriter *writer, const char *name,
                               int nx, int ny, double dx, double dy)
{
    assert(writer != NULL);
    assert(name != NULL);
    assert(nx > 0 && ny > 0);

    fprintf(writer->output, "%%SR%s,%d,%d,%.4f,%.4f*%%\n",
            name, nx, ny, dx, dy);
}

void gerber_writer_finish(GerberWriter *writer)
{
    assert(writer != NULL);
    /* Ensure any open region is closed */
    if (writer->region_active) {
        fprintf(writer->output, "G37*\n");
        writer->region_active = 0;
    }
    fprintf(writer->output, "M02*\n");
    fflush(writer->output);

    /* Free X2 part attributes if we own them */
    if (writer->x2_enabled) {
        x2_file_attr_free(&writer->x2_attr);
    }
}

/* ─── Layer Generation Functions ────────────────────────────────── */

int gerber_gen_copper_layer(const char *filename,
                            const PCBRegion *regions, int n_regions,
                            int layer_num, const char *board_name)
{
    assert(filename != NULL);
    assert(regions != NULL || n_regions == 0);

    FILE *fp = fopen(filename, "w");
    if (fp == NULL) {
        return -1;
    }

    GerberWriter writer;
    gerber_writer_init(&writer, fp, GERBER_UNIT_MM, 3, 4,
                       GERBER_ZERO_LEADING);

    /* Set X2 file attributes */
    X2FileAttribute attr;
    x2_file_attr_init(&attr);
    attr.function     = X2_FUNC_COPPER;
    attr.layer_number = layer_num;
    if (board_name != NULL) {
        strncpy(attr.part_name, board_name, sizeof(attr.part_name) - 1);
    }
    gerber_writer_set_x2(&writer, &attr);

    /* Define generic round aperture and rectangular trace aperture */
    int ap_round = gerber_writer_add_aperture(&writer, APERTURE_CIRCLE,
                                              0.3, 0, 0, 0);
    int ap_rect  = gerber_writer_add_aperture(&writer, APERTURE_RECTANGLE,
                                              0.3, 0.3, 0, 0);
    /* For very thin regions, we need a smaller aperture too */
    int ap_fine  = gerber_writer_add_aperture(&writer, APERTURE_CIRCLE,
                                              0.1, 0, 0, 0);

    /* Emit each region as a filled polygon (G36..G37) */
    for (int i = 0; i < n_regions; i++) {
        const PCBRegion *region = &regions[i];

        if (region->n_vertices < 3) continue;

        /* Select the aperture for the region outline stroke */
        gerber_writer_select_aperture(&writer, (region->min_width_mm < 0.2) ? ap_fine : ap_round);

        gerber_writer_comment(&writer, region->net_name);

        gerber_writer_begin_region(&writer);

        /* Draw the closed polygon */
        for (int v = 0; v < region->n_vertices; v++) {
            gerber_writer_draw_to(&writer,
                                  region->vertices[v].x,
                                  region->vertices[v].y);
        }

        gerber_writer_end_region(&writer);
    }

    /* Close file */
    gerber_writer_finish(&writer);
    fclose(fp);

    return 0;
}

int gerber_gen_soldermask(const char *filename,
                          const PCBPad *pads, int n_pads,
                          double expansion_mm, int is_top)
{
    assert(filename != NULL);
    assert(pads != NULL || n_pads == 0);

    FILE *fp = fopen(filename, "w");
    if (fp == NULL) {
        return -1;
    }

    GerberWriter writer;
    gerber_writer_init(&writer, fp, GERBER_UNIT_MM, 3, 4,
                       GERBER_ZERO_LEADING);

    /* X2 attributes */
    X2FileAttribute attr;
    x2_file_attr_init(&attr);
    attr.function     = is_top ? X2_FUNC_SOLDERMASK_TOP : X2_FUNC_SOLDERMASK_BOT;
    attr.layer_number = 1;
    gerber_writer_set_x2(&writer, &attr);

    /* Solder mask is typically a negative image.
     * We draw clearance openings at each pad position. */
    gerber_writer_set_polarity(&writer, GERBER_POLARITY_CLEAR);

    /* Create appropriate aperture for pad clearances */
    /* We'll use flash operations for circular pads and rectangles for others */

    for (int i = 0; i < n_pads; i++) {
        const PCBPad *pad = &pads[i];

        /* Skip pads on wrong side */
        if (is_top && pad->layer != 1) continue;
        if (!is_top && pad->layer != 2) continue;

        /* SMD pads get mask clearance */
        if (pad->tech == PAD_TECH_PTH && pad->hole_diameter > 0) {
            /* For PTH pads, mask opening is the annular ring plus expansion */
            double mask_size = pad->width_mm + 2.0 * expansion_mm;

            /* Define a circular aperture for this pad size */
            char macro_name[32];
            snprintf(macro_name, sizeof(macro_name), "MC%d", i);

            /* Flash the mask opening */
            gerber_writer_flash_at(&writer, pad->position.x, pad->position.y);
        } else {
            /* SMD pad — rectangular mask opening */
            double mask_w = pad->width_mm + 2.0 * expansion_mm;
            double mask_h = (pad->height_mm > 0 ? pad->height_mm : pad->width_mm)
                            + 2.0 * expansion_mm;

            /* Flash a rectangle aperture */
            gerber_writer_flash_at(&writer, pad->position.x, pad->position.y);
        }
    }

    gerber_writer_finish(&writer);
    fclose(fp);

    return 0;
}

int gerber_gen_silkscreen(const char *filename,
                          const PCBLineSegment *outlines, int n_outlines,
                          int is_top)
{
    assert(filename != NULL);
    assert(outlines != NULL || n_outlines == 0);

    FILE *fp = fopen(filename, "w");
    if (fp == NULL) {
        return -1;
    }

    GerberWriter writer;
    gerber_writer_init(&writer, fp, GERBER_UNIT_MM, 3, 4,
                       GERBER_ZERO_LEADING);

    /* X2 attributes */
    X2FileAttribute attr;
    x2_file_attr_init(&attr);
    attr.function     = is_top ? X2_FUNC_SILKSCREEN_TOP : X2_FUNC_SILKSCREEN_BOT;
    attr.layer_number = 1;
    gerber_writer_set_x2(&writer, &attr);

    /* Define a thin line aperture for silkscreen */
    gerber_writer_add_aperture(&writer, APERTURE_CIRCLE, 0.15, 0, 0, 0);
    gerber_writer_select_aperture(&writer, 10);

    /* Draw all silkscreen line segments */
    for (int i = 0; i < n_outlines; i++) {
        gerber_writer_move_to(&writer,
                              outlines[i].start.x,
                              outlines[i].start.y);
        gerber_writer_draw_to(&writer,
                              outlines[i].end.x,
                              outlines[i].end.y);
    }

    gerber_writer_finish(&writer);
    fclose(fp);

    return 0;
}

int gerber_gen_profile(const char *filename,
                       const GerberPointD *outline, int n_points)
{
    assert(filename != NULL);
    assert(outline != NULL);
    assert(n_points >= 3);

    FILE *fp = fopen(filename, "w");
    if (fp == NULL) {
        return -1;
    }

    GerberWriter writer;
    gerber_writer_init(&writer, fp, GERBER_UNIT_MM, 3, 4,
                       GERBER_ZERO_LEADING);

    /* X2 profile function */
    X2FileAttribute attr;
    x2_file_attr_init(&attr);
    attr.function = X2_FUNC_PROFILE;
    attr.layer_number = 1;
    gerber_writer_set_x2(&writer, &attr);

    /* Draw the closed board outline */
    gerber_writer_add_aperture(&writer, APERTURE_CIRCLE, 0.1, 0, 0, 0);
    gerber_writer_select_aperture(&writer, 10);

    gerber_writer_move_to(&writer, outline[0].x, outline[0].y);
    for (int i = 1; i < n_points; i++) {
        gerber_writer_draw_to(&writer, outline[i].x, outline[i].y);
    }
    /* Close the polygon */
    gerber_writer_draw_to(&writer, outline[0].x, outline[0].y);

    gerber_writer_finish(&writer);
    fclose(fp);

    return 0;
}
